name: Deploy Pipeline - Test

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Commit SHA or branch to deploy (default: develop)'
        required: false
        default: 'develop'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'

      - name: Define image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Build Docker image (testing)
        run: |
          gcloud builds submit \
            --project="${{ secrets.GCP_PROJECT }}" \
            --config cloudbuild.yaml \
            --substitutions=_BUILD_ENV=testing,_TAG=$IMAGE_TAG

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy brasil-transparente-frontend-test \
            --image gcr.io/${{ secrets.GCP_PROJECT }}/frontend:$IMAGE_TAG \
            --region="${{ secrets.REGION }}" \
            --platform=managed \
            --allow-unauthenticated